name: Manual - Vcpkg Install or Upgrade

on:
  workflow_dispatch:

jobs:
  manual-vcpkg-prepare:
    name: manual-vcpkg-prepare
    runs-on: macos-latest

    env:
      VCPKG_ROOT: '${{ github.workspace }}/vcpkg'
      BUILD_TYPE: Release

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/cache@v3
      id: vcpkg-cache
      with:
        path: |
          ${{ github.workspace }}/vcpkg
          ${{ github.workspace }}/build
        key: vcpkg-cache-${{ runner.os }}

    - name: Vcpkg - Prepare Tool
      working-directory: ${{ github.workspace }}
      run: |
        if [ ! -d vcpkg ]; then
          git clone https://github.com/Microsoft/vcpkg.git --depth=1
        fi
        cd vcpkg
        git clean -f
        git pull
        ./bootstrap-vcpkg.sh
